### ISSUE TITLE
Is rbclipper considered thread safe?

### ISSUE THREAD

**Issue by PatrickFranken** [mieko/rbclipper#13]
I noticed some wired behavior in a threaded application and asked myself if it is maybe related to the clipper C extension. From my limited C experience it's hard to see whether rbclipper.cpp instantiates a new instance on .new or not. So is rbclipper thread safe?

**Comment by mieko** [comment]
Hi, Patrick,

Both rbclipper and the underlying Clipper *should* be threadsafe.  

I haven't looked over the code in years, but the instantiation you're looking for is here:
https://github.com/mieko/rbclipper/blob/f5d14876d944d2c420573e60e2d681d5dc85d9bd/ext/clipper/rbclipper.cpp#L87-L94

It looks like a pretty normal pattern that's threadsafe

I skimmed over the included clipper.cpp again, and don't see any static or global objects (besides constants).

**Comment by PatrickFranken** [comment]
Hi Mike,

thanks for your swift reply! Totally makes sense. So rbclipper is out of my scope looking for the issue, that's a good thing :)
